name: Export Shortcut

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sign:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          shortcuts --help
